server:
  port: 9093

spring:
  application:
    name: msvc-auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authdb #Aca hay que ver que tabla usamos, porque debe tener 
    username: postgres                        #acceso a los ususarios, asi los valida
    password: mateamargo
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  