server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: events
          uri: http://localhost:9091
          predicates:
            - Path=/api/event/**

        - id: artists
          uri: http://localhost:8091
          predicates:
            - Path=/api/artist/**

        #- id: auth
        #  uri: http://localhost:9093
        #  predicates:
        #    - Path=/api/auth/**

        - id: users
          uri: http://localhost:9092
          predicates:
            - Path=/api/user/**

        - id: admin
          uri: http://localhost:9092
          predicates:
            - Path=/api/admin/**

security:
  jwt:
    #secret: mate_amargo123
    #expiration: 864000000 # 10 días en milisegundos
    whitelist:
      - /actuator/**
      - /api/auth/**
      - /api/public/**
      - /api/artist/all
      - /api/event/all

eureka:
  client:
    register-with-eureka: false
