server:
  port: 9092

spring:
  application:
    name: msvc-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: mate_amargo123  #Despues descomentar
    expiration: 864000000 # 10 día en milisegundos

# En: microservice-config/configurations/msvc-user.yml

logging:
  level:
    # Nivel general en INFO
    root: INFO
    # Nivel específico para TU código en DEBUG (más detallado)
    com.microservice.user: DEBUG # O al menos INFO


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka